#!/bin/bash

case "$1" in
--smudge)
	date=$(git log --pretty=format:"%ai" -1)
	sed -e "s,\\\$Date:[^$]*\\\$,\\\$Date: $date \\\$,g"
	;;
--clean)
	sed -e "s,\\\$Date:[^\\\$]*\\\$,\\\$Date: YYYY-MM-DD TIME \\\$,g"
	;;
esac
