#!/bin/bash

case "$1" in
--smudge)
	sha=$(git log -1 | head -n 1 | cut -d' ' -f2)
	sed -e "s,\\\$SHA-1:[^$]*\\\$,\\\$SHA-1: $sha \\\$,g"
	;;
--clean)
	sed -e "s,\\\$SHA-1:[^\\\$]*\\\$,\\\$SHA-1: xxxxxxx \\\$,g"
	;;
esac
