#!/bin/sh

base=`basename $1 .fig`

for i in `cat $base.depth`; do
  echo Creating $base-$i.pdf ...
  fig2dev -L pstex -D +$i -m 1.9 -s 7 $base.fig > $base-$i.eps
  fig2dev -L pstex_t -D +$i -m 1.9 -s 7 $base.fig > $base-$i.tex
  epstopdf $base-$i.eps
done
